// Global
export const DATA_LOAD_ERROR = "DATA_LOAD_ERROR";

// Category
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_PAGINATE = "CATEGORY_PAGINATE";
export const CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND";
export const GET_CATEGORIES = "GET_CATEGORY";
export const CATEGORY_LOAD_ERROR = "CATEGORY_LOAD_ERROR";

//user
export const GET_LOGGEDIN_USER = "GET_LOGGEDIN_USER"
// export const 
export const GET_USER = "GET_USER";
export const USER_LOADING = "USER_LOADING";
export const FILTER_USERS = "FILTER_USERS";
// export const


//login
export const USER_LOGIN = "USER_LOGIN";
export const LOG_OUT = "LOG_OUT";


export const GET_ROLES = "GET_ROLES";
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const ROLES_LOADING = "ROLES_LOADING";
export const FILTER_ROLES = "FILTER_ROLES";

export const GET_ALL_PERMISSIONS = "GET_ALL_PERMISSIONS";
// export const


//units
export const GET_ALL_UNITS = "GET_ALL_UNITS"
export const ADD_UNIT = "ADD_UNIT"
export const GET_UNITS = "GET_UNITS"
export const GET_ALL_THRESHOLD = "GET_ALL_THRESHOLD";

// Transactions
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const TRANSACTION_LOADING = "TRANSACTION_LOADING";
export const TRANSACTION_LOAD_ERROR = "TRANSACTION_LOAD_ERROR";
// End Transactions

//Branches
export const GET_ALL_BRANCHES = "GET_ALL_BRANCHES";

//PRODUCTS
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

//INVENTORY
export const GET_PENDING_TRANSACTIONS = "GET_ALL_PENDING_TRANSACTIONS";

//INVENTORY VIEW 
export const GET_INVENTORY_VIEW_SUMMARY = "GET_INVENTORY_VIEW_SUMMARY"
export const INVENTORY_VIEW_LOADING_ERROR = "INVENTORY_VIEW_LOADING_ERROR"
export const INVENTORY_VIEW_LOADING = "INVENTORY_VIEW_LOADING"