// Category
export const GET_CATEGORY = "GET_CATEGORY";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_PAGINATE = "CATEGORY_PAGINATE";
export const CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CATEGORY_LOAD_ERROR = "CATEGORY_LOAD_ERROR";

//user
export const GET_USERS = "GET_USERS";
export const USERS_LOADING = "USERS_LOADING"
export const FILTER_USERS = "FILTER_USERS"
// export const 
